import type { TopicRecipe } from "./types.js";

/**
 * Built-in topic catalog. Users can enable/disable, reorder, edit, or delete
 * these, and add their own. `enabled: true` topics show as tabs by default;
 * the rest are available in Settings → 주제 관리 to turn on.
 *
 * githubTopics carry the strongest precision; include/exclude refine further.
 * All topic tags here were validated against the live GitHub API.
 */
export const DEFAULT_TOPICS: TopicRecipe[] = [
  {
    id: "preset-llm",
    name: "LLM",
    include: ["llm", "large language model"],
    exclude: ["course", "tutorial-list", "awesome-list"],
    githubTopics: ["llm", "large-language-models"],
    minStars: 10,
    recentDays: 90,
    enabled: true,
    subtopics: [
      { id: "inference", name: "추론·서빙", githubTopics: ["llm-inference", "inference", "llm-serving"] },
      { id: "rag", name: "RAG", githubTopics: ["rag", "retrieval-augmented-generation"] },
      { id: "finetune", name: "파인튜닝", githubTopics: ["fine-tuning", "llm-training", "lora"] },
      { id: "agent", name: "에이전트", githubTopics: ["llm-agent", "ai-agent", "agents"] },
      { id: "app", name: "앱·챗", githubTopics: ["chatbot", "llm-app", "chatgpt"] },
    ],
    isPreset: true,
  },
  {
    id: "preset-mcp",
    name: "MCP",
    include: ["model context protocol", "mcp server", "mcp client"],
    exclude: ["minecraft", "minecraft-mod", "management control panel"],
    githubTopics: ["model-context-protocol", "mcp-server", "mcp"],
    minStars: 5,
    recentDays: 90,
    enabled: true,
    subtopics: [
      { id: "server", name: "서버", githubTopics: ["mcp-server", "mcp-servers"] },
      { id: "client", name: "클라이언트", githubTopics: ["mcp-client"] },
      { id: "framework", name: "프레임워크·SDK", githubTopics: ["mcp-framework", "mcp-sdk"] },
      { id: "registry", name: "레지스트리·목록", githubTopics: ["mcp-registry", "awesome-mcp"] },
    ],
    isPreset: true,
  },
  {
    id: "preset-skills",
    name: "Skills",
    include: ["agent skills", "ai agent skills", "claude skills"],
    exclude: ["resume", "game", "soft skills", "interview"],
    githubTopics: ["agent-skills", "claude-skills"],
    minStars: 5,
    recentDays: 90,
    enabled: true,
    subtopics: [
      { id: "claude", name: "Claude Skills", githubTopics: ["claude-skills"] },
      { id: "agent", name: "에이전트 스킬", githubTopics: ["agent-skills"] },
      { id: "tools", name: "툴·플러그인", githubTopics: ["ai-tools", "agent-tools", "llm-tools"] },
    ],
    isPreset: true,
  },
  {
    id: "preset-agents",
    name: "AI Agents",
    include: ["ai agent", "autonomous agent", "multi-agent"],
    exclude: ["tutorial-list", "awesome-list"],
    githubTopics: ["ai-agents", "ai-agent", "autonomous-agents"],
    minStars: 20,
    recentDays: 90,
    enabled: false,
    isPreset: true,
  },
  {
    id: "preset-rag",
    name: "RAG",
    include: ["retrieval augmented generation", "rag"],
    exclude: ["awesome-list"],
    githubTopics: ["rag", "retrieval-augmented-generation"],
    minStars: 20,
    recentDays: 90,
    enabled: false,
    isPreset: true,
  },
  {
    id: "preset-vectordb",
    name: "Vector DB",
    include: ["vector database", "embeddings search"],
    exclude: [],
    githubTopics: ["vector-database", "vector-search", "embeddings"],
    minStars: 20,
    recentDays: 120,
    enabled: false,
    isPreset: true,
  },
  {
    id: "preset-prompt",
    name: "Prompt Engineering",
    include: ["prompt engineering", "prompts"],
    exclude: ["awesome-list"],
    githubTopics: ["prompt-engineering", "prompts"],
    minStars: 30,
    recentDays: 120,
    enabled: false,
    isPreset: true,
  },
  {
    id: "preset-diffusion",
    name: "Diffusion / 이미지 생성",
    include: ["diffusion model", "text to image", "image generation"],
    exclude: [],
    githubTopics: ["diffusion-models", "stable-diffusion", "text-to-image"],
    minStars: 30,
    recentDays: 120,
    enabled: false,
    isPreset: true,
  },
  {
    id: "preset-finetune",
    name: "Fine-tuning",
    include: ["fine-tuning", "lora", "peft"],
    exclude: [],
    githubTopics: ["fine-tuning", "lora", "peft"],
    minStars: 20,
    recentDays: 120,
    enabled: false,
    isPreset: true,
  },
  {
    id: "preset-voice",
    name: "Voice / STT·TTS",
    include: ["speech to text", "text to speech", "voice ai"],
    exclude: [],
    githubTopics: ["speech-to-text", "text-to-speech", "speech-recognition"],
    minStars: 20,
    recentDays: 120,
    enabled: false,
    isPreset: true,
  },
  {
    id: "preset-frontend",
    name: "Frontend",
    include: ["frontend", "web ui"],
    exclude: ["awesome-list"],
    githubTopics: ["frontend", "react", "vue", "svelte"],
    minStars: 50,
    recentDays: 120,
    enabled: false,
    subtopics: [
      { id: "react", name: "React", githubTopics: ["react", "reactjs", "nextjs"] },
      { id: "vue", name: "Vue", githubTopics: ["vue", "vuejs", "nuxt"] },
      { id: "svelte", name: "Svelte", githubTopics: ["svelte", "sveltekit"] },
      { id: "css", name: "CSS·UI", githubTopics: ["css", "tailwindcss", "ui-components"] },
    ],
    isPreset: true,
  },
  {
    id: "preset-backend",
    name: "Backend",
    include: ["backend", "web framework", "api server"],
    exclude: ["awesome-list"],
    githubTopics: ["backend", "api", "web-framework"],
    minStars: 50,
    recentDays: 120,
    enabled: false,
    subtopics: [
      { id: "node", name: "Node.js", githubTopics: ["nodejs", "express", "nestjs"] },
      { id: "python", name: "Python", githubTopics: ["fastapi", "django", "flask"] },
      { id: "go", name: "Go", githubTopics: ["golang", "gin", "go-web"] },
      { id: "rust", name: "Rust", githubTopics: ["rust", "axum", "actix"] },
    ],
    isPreset: true,
  },
  {
    id: "preset-mobile",
    name: "Mobile",
    include: ["mobile app", "ios", "android"],
    exclude: ["awesome-list"],
    githubTopics: ["mobile", "flutter", "react-native", "swift"],
    minStars: 50,
    recentDays: 120,
    enabled: false,
    subtopics: [
      { id: "flutter", name: "Flutter", githubTopics: ["flutter", "dart"] },
      { id: "rn", name: "React Native", githubTopics: ["react-native", "expo"] },
      { id: "ios", name: "iOS", githubTopics: ["ios", "swift", "swiftui"] },
      { id: "android", name: "Android", githubTopics: ["android", "kotlin", "jetpack-compose"] },
    ],
    isPreset: true,
  },
  {
    id: "preset-devops",
    name: "DevOps",
    include: ["devops", "kubernetes", "ci cd"],
    exclude: ["awesome-list"],
    githubTopics: ["devops", "kubernetes", "docker"],
    minStars: 50,
    recentDays: 120,
    enabled: false,
    subtopics: [
      { id: "k8s", name: "Kubernetes", githubTopics: ["kubernetes", "k8s", "helm"] },
      { id: "iac", name: "IaC", githubTopics: ["terraform", "pulumi", "ansible"] },
      { id: "cicd", name: "CI/CD", githubTopics: ["ci-cd", "github-actions", "gitops"] },
      { id: "observability", name: "관측성", githubTopics: ["observability", "monitoring", "prometheus"] },
    ],
    isPreset: true,
  },
  {
    id: "preset-security",
    name: "Security",
    include: ["security", "cybersecurity"],
    exclude: ["awesome-list"],
    githubTopics: ["security", "cybersecurity", "infosec"],
    minStars: 50,
    recentDays: 120,
    enabled: false,
    subtopics: [
      { id: "pentest", name: "Pentest", githubTopics: ["penetration-testing", "pentesting", "red-team"] },
      { id: "appsec", name: "AppSec", githubTopics: ["appsec", "sast", "vulnerability"] },
      { id: "crypto", name: "암호", githubTopics: ["cryptography", "encryption"] },
    ],
    isPreset: true,
  },
];
